from collections.abc import Sequence
from pathlib import Path
import re

import numpy as np
import pandas as pd
import polars as pl
import polars.selectors as cs
from tableone import TableOne


GHM_CODE_TO_LABEL_FR: dict[str, str] = {
    "01C": "neurochirurgie",
    "01M": "neurologie",
    "01K": "Embolisation cerebrales ou medullaire",
    "03C": "chirurgie ORL",
    "04M": "Pathologie Respiratoire",
    "05C": "Chirurgie cardio-vasculaire (hors endoprothese)",
    "05K": "Endoprothese vasculaire",
    "05M": "Cardiologie",
    "06M": "Atteinte digestive",
    "07M": "Atteinte hépatobiliaire et pancréatique",
    "08C": "Chirurgie Orthopédique et Amputations",
    "10M": "Diabete et troubles metaboliques",
    "11C": "Chirurgie Urologique",
    "11M": "Pyelonéphrite non chirurgicale et insuffisance rénale",
    "18M": "Maladie infectieuse et sepsis",
    "21M": "Intoxication",
    "26C": "Polytraumatisme",
    "26M": "Polytraumatisme",
    "27C": "Transplantation organe solide",
}

GHM_CODE_TO_LABEL: dict[str, str] = {
    "01C": "Neurosurgery",
    "01M": "Neurology",
    "01K": "Cerebral or Spinal Embolization",
    "03C": "ENT Surgery",
    "04M": "Respiratory Pathology",
    "05C": "Cardiovascular Surgery (excluding Endoprosthesis)",
    "05K": "Vascular Endoprosthesis",
    "05M": "Cardiology",
    "06M": "Gastroenterology",
    "07M": "Gastroenterology",
    "08C": "Orthopedic Surgery and Amputations",
    "10M": "Diabetes and Metabolic Disorders",
    "11C": "Urological Surgery",
    "11M": "Non-surgical Pyelonephritis and Renal Insufficiency",
    "18M": "Infectious Disease and Sepsis",
    "21M": "Poisoning",
    "26C": "Polytrauma",
    "26M": "Polytrauma",
    "27C": "Solid Organ Transplantation",
}


ENTRY_MODE_TO_LABEL: dict[str, str] = {
    "Domicile": "Home or Emergency",
    "Urgence": "Home or Emergency",
    "Transfert MCO": "Hospital Transfer",
    "Mutation MCO": "Inter-hospital Transfer",
}


FR_TO_EN: dict[str, str] = {
    # Gender
    "Féminin": "Female",
    "Masculin": "Male",
}


def _get_entry_mode_label(mode: str) -> str:
    """Map a raw ICU entry mode to a grouped, human-readable label.

    Args:
        mode: Raw entry mode value from the dataset.

    Returns:
        The grouped label for the entry mode.
    """
    return ENTRY_MODE_TO_LABEL.get(mode, "Others")


def rename_ghm_dummies(columns: list[str]) -> dict[str, str]:
    """Rename GHM dummy columns to human-readable ICU_ghm labels.

    Each dummy column produced by Polars (e.g. ``icu_ghm_f3_01C``) is
    mapped to a readable name following the pattern ``icu_ghm_<label>``.
    Codes that are not explicitly defined fall back to ``icu_ghm_Others``.

    Args:
        columns: GHM dummy column names generated by ``to_dummies``
            (e.g. ``["icu_ghm_f3_01C", "icu_ghm_f3_21M"]``).

    Returns:
        Dictionary mapping original dummy column names to their readable
        counterparts. Only columns whose name starts with ``icu_ghm_f3_``
        are included.

    Examples:
        >>> rename_ghm_dummies(["icu_ghm_f3_01C", "icu_ghm_f3_99Z"])
        {
            "icu_ghm_f3_01C": "icu_ghm_neurochirurgie",
            "icu_ghm_f3_99Z": "icu_ghm_Others",
        }
    """
    result: dict[str, str] = {}

    for column in columns:
        if not column.startswith("icu_ghm_f3_"):
            continue

        code = column.removeprefix("icu_ghm_f3_")
        label = GHM_CODE_TO_LABEL.get(code, "Others")
        result[column] = f"icu_ghm_{label}"

    return result


def encode_categorical_features(
    dataframe: pl.DataFrame,
    feature_mode: str,
    features_to_keep: Sequence[str],
) -> tuple[pl.DataFrame, list[str], list[str]]:
    """Encode categorical model features.

    Admission type is always one-hot encoded. GHM prefixes and ICU entry
    modes are encoded in ``Mode Commonly Used``. Gender is encoded in the
    custom and complete feature modes.

    Args:
        dataframe: Input patient time-series dataframe.
        feature_mode: Selected feature configuration.
        features_to_keep: Features selected before categorical encoding.

    Returns:
        A tuple containing:
            - The transformed dataframe.
            - The updated feature list.
            - The names of all generated dummy columns.
    """
    processed_dataframe = dataframe
    updated_features = list(features_to_keep)
    generated_dummy_columns: list[str] = []

    processed_dataframe = (
        processed_dataframe
        .with_columns(
            pl.col("admission_type").fill_null("Unknown"),
        )
        .to_dummies(columns=["admission_type"])
    )

    admission_dummy_columns = [
        column
        for column in processed_dataframe.columns
        if column.startswith("admission_type_")
    ]
    generated_dummy_columns.extend(admission_dummy_columns)

    if "admission_type" in updated_features:
        updated_features.remove("admission_type")
        updated_features.extend(admission_dummy_columns)

    if feature_mode == "Mode Commonly Used":
        processed_dataframe = processed_dataframe.with_columns(
            pl.col("icu_ghm")
            .list.first()
            .cast(pl.String)
            .str.head(3)
            .fill_null("Unknown")
            .alias("icu_ghm_f3"),
        )

        ghm_dummies = (
            processed_dataframe
            .select("icu_ghm_f3")
            .to_dummies(columns=["icu_ghm_f3"])
        )

        unknown_ghm_column = "icu_ghm_f3_Unknown"
        if unknown_ghm_column in ghm_dummies.columns:
            ghm_dummies = ghm_dummies.drop(unknown_ghm_column)

        # Rename GHM dummy columns to human-readable labels (merge duplicates)
        ghm_rename_mapping = rename_ghm_dummies(ghm_dummies.columns)

        # Group columns by target name so duplicates are summed rather than
        # causing a Polars DuplicateError.
        target_groups: dict[str, list[str]] = {}
        for original, target in ghm_rename_mapping.items():
            target_groups.setdefault(target, []).append(original)

        merged_columns: list[pl.Expr] = []
        for target, sources in target_groups.items():
            if len(sources) == 1:
                merged_columns.append(pl.col(sources[0]).alias(target))
            else:
                merged_columns.append(
                    pl.sum_horizontal(*sources).alias(target)
                )

        ghm_dummies = ghm_dummies.select(merged_columns)

        # Map entry modes to grouped labels (nulls and unknown values -> Other)
        processed_dataframe = processed_dataframe.with_columns(
            pl.col("icu_mode_entree")
            .fill_null("Others")
            .replace_strict(
                {k: v for k, v in ENTRY_MODE_TO_LABEL.items()},
                default="Others",
                return_dtype=pl.String,
            )
            .alias("icu_mode_entree_label")
        )

        entry_mode_dummies = (
            processed_dataframe
            .select("icu_mode_entree_label")
            .to_dummies(columns=["icu_mode_entree_label"])
        )

        # Rename entry mode dummy columns to icu_mode_entree_<label>
        entry_rename_mapping = {
            f"icu_mode_entree_label_{label}": f"icu_mode_entree_{label}"
            for label in ["Home or Emergency", "Hospital Transfer", "Inter-hospital Transfer", "Others"]
        }
        entry_mode_dummies = entry_mode_dummies.rename(
            {k: v for k, v in entry_rename_mapping.items() if k in entry_mode_dummies.columns}
        )

        new_dummy_columns = [
            *ghm_dummies.columns,
            *entry_mode_dummies.columns,
        ]
        generated_dummy_columns.extend(new_dummy_columns)

        source_columns = {
            "icu_ghm",
            "icu_ghm_f3",
            "icu_mode_entree",
            "icu_mode_entree_label",
        }

        updated_features = [
            feature
            for feature in updated_features
            if feature not in source_columns
        ]
        updated_features.extend(new_dummy_columns)

        existing_source_columns = [
            column
            for column in source_columns
            if column in processed_dataframe.columns
        ]

        processed_dataframe = pl.concat(
            [
                processed_dataframe.drop(existing_source_columns),
                ghm_dummies,
                entry_mode_dummies,
            ],
            how="horizontal",
        )

    gender_feature_modes = {
        "Mode Custom",
        "Mode All Without pmsi",
        "Mode All",
    }

    if feature_mode in gender_feature_modes:
        processed_dataframe = (
            processed_dataframe
            .with_columns(
                pl.col("gender").fill_null("Unknown"),
            )
            .to_dummies(columns=["gender"])
        )

        gender_dummy_columns = [
            column
            for column in processed_dataframe.columns
            if column.startswith("gender_")
        ]
        generated_dummy_columns.extend(gender_dummy_columns)

        # Rename gender dummy columns using FR_TO_EN mapping
        gender_rename_mapping: dict[str, str] = {}
        for col in gender_dummy_columns:
            value = col.removeprefix("gender_")
            if value in FR_TO_EN:
                gender_rename_mapping[col] = f"gender_{FR_TO_EN[value]}"
        if gender_rename_mapping:
            processed_dataframe = processed_dataframe.rename(gender_rename_mapping)
            generated_dummy_columns = [
                gender_rename_mapping.get(col, col)
                for col in generated_dummy_columns
            ]
            if "gender" in updated_features:
                updated_features.remove("gender")
                updated_features.extend(generated_dummy_columns)
            else:
                updated_features = [
                    gender_rename_mapping.get(f, f) for f in updated_features
                ]
        else:
            if "gender" in updated_features:
                updated_features.remove("gender")
                updated_features.extend(gender_dummy_columns)

    processed_dataframe = processed_dataframe.with_columns(
        cs.numeric().cast(pl.Float64),
        cs.boolean().cast(pl.Float64),
    )

    return (
        processed_dataframe,
        list(dict.fromkeys(updated_features)),
        list(dict.fromkeys(generated_dummy_columns)),
    )


def build_static_feature_list(
    dataframe: pl.DataFrame,
    generated_dummy_columns: Sequence[str],
    config_mode_name: str,
    final_features: Sequence[str] | None = None,
) -> list[str]:
    """Build the list of patient-level static features.

    Static features are excluded from time-series feature extraction and are
    described directly in the cohort summary table.

    Args:
        dataframe: Fully preprocessed time-series dataframe.
        generated_dummy_columns: Dummy columns created during categorical
            encoding.
        config_mode_name: Windowing or resampling configuration name.
        final_features: Optional final feature list used to filter the result.

    Returns:
        Static feature names available in the requested feature set.

    Raises:
        ValueError: If an expected static feature is absent from the dataframe
            when no final feature list is provided.
    """
    static_features = [
        *generated_dummy_columns,
        "age",
        "score_glasgow"
    ]

    if config_mode_name == "resampling_X_points":
        static_features.append("real_time_hours")
    elif (
        config_mode_name
        == "resampling_x_points_alea_lomax_prio_24h_no-fill"
    ):
        static_features.append("observed_duration")

    static_features = list(dict.fromkeys(static_features))

    if final_features is not None:
        return [
            feature
            for feature in static_features
            if feature in final_features
        ]

    missing_features = [
        feature
        for feature in static_features
        if feature not in dataframe.columns
    ]

    if missing_features:
        raise ValueError(
            "Static features are missing from the preprocessed dataframe: "
            f"{missing_features}"
        )

    return static_features


def add_variable_type_sections(
    table_dataframe: pd.DataFrame,
    continuous_features: Sequence[str],
    categorical_features: Sequence[str],
) -> pd.DataFrame:
    """Add continuous and categorical section headers to a TableOne result.

    The summary statistics are left unchanged. Only the row layout is
    reorganized to make the distinction between continuous and categorical
    variables explicit.

    Args:
        table_dataframe: DataFrame produced by ``TableOne.tableone``.
        continuous_features: Variables displayed as continuous.
        categorical_features: Variables displayed as categorical.

    Returns:
        A copy of the TableOne dataframe containing explicit section rows.

    Raises:
        ValueError: If the TableOne dataframe does not use the expected
            two-level row index.
    """
    if (
        not isinstance(table_dataframe.index, pd.MultiIndex)
        or table_dataframe.index.nlevels != 2
    ):
        raise ValueError(
            "The TableOne result must have a two-level MultiIndex."
        )

    table_dataframe = table_dataframe.copy()
    first_index_level = (
        table_dataframe.index
        .get_level_values(0)
        .astype(str)
    )

    def create_section_row(title: str) -> pd.DataFrame:
        """Create an empty row used as a section header."""
        section_index = pd.MultiIndex.from_tuples(
            [(title, "")],
            names=table_dataframe.index.names,
        )

        return pd.DataFrame(
            "",
            index=section_index,
            columns=table_dataframe.columns,
        )

    def select_feature_rows(features: Sequence[str]) -> list[pd.DataFrame]:
        """Select complete TableOne row blocks for the requested features."""
        selected_blocks: list[pd.DataFrame] = []

        for feature in features:
            pattern = rf"^{re.escape(feature)}(?:,|$)"
            matching_rows = first_index_level.str.match(pattern)

            if matching_rows.any():
                selected_blocks.append(table_dataframe.loc[matching_rows])

        return selected_blocks

    output_blocks: list[pd.DataFrame] = []

    sample_size_rows = first_index_level == "n"
    if sample_size_rows.any():
        output_blocks.append(table_dataframe.loc[sample_size_rows])

    continuous_blocks = select_feature_rows(continuous_features)
    if continuous_blocks:
        output_blocks.append(create_section_row("Continuous variables"))
        output_blocks.extend(continuous_blocks)

    categorical_blocks = select_feature_rows(categorical_features)
    if categorical_blocks:
        output_blocks.append(create_section_row("Categorical variables"))
        output_blocks.extend(categorical_blocks)

    return pd.concat(output_blocks)



def _any_true_during_stay(
    columns: Sequence[str],
    output_name: str,
) -> pl.Expr:
    """Return whether any input flag is true at least once during a stay.

    The expression first combines the requested columns row by row, then
    aggregates the resulting boolean values over every row of the patient
    group. Null and non-convertible values are treated as ``False``.

    Args:
        columns:
            Boolean-like columns to inspect.
        output_name:
            Name assigned to the resulting patient-level flag.

    Returns:
        A Polars aggregation expression yielding one boolean per patient.
    """
    if not columns:
        raise ValueError(
            f"At least one source column is required for {output_name!r}."
        )

    row_has_true = pl.any_horizontal(
        [
            pl.col(column)
            .cast(pl.Boolean, strict=False)
            .fill_null(False)
            for column in columns
        ]
    )

    return row_has_true.any().alias(output_name)


def _build_patient_level_clinical_flags(
    dataframe: pl.DataFrame,
    patient_col: str,
) -> pl.DataFrame:
    """Build one row of clinical history flags per patient.

    ``had_ventilation`` is true when at least one ventilation source column
    is true on at least one row of the patient's stay.
    """
    aggregation_expressions: list[pl.Expr] = []

    ventilation_columns = [
        column
        for column in ("is_cvvhf", "is_hdi")
        if column in dataframe.columns
    ]

    if ventilation_columns:
        aggregation_expressions.append(
            _any_true_during_stay(
                columns=ventilation_columns,
                output_name="had_ventilation",
            )
        )

    if "dobu_dose_poids" in dataframe.columns:
        aggregation_expressions.append(
            pl.col("dobu_dose_poids")
            .is_not_null()
            .any()
            .alias("had_nad")
        )

    if "is_conscious" in dataframe.columns:
        aggregation_expressions.append(
            _any_true_during_stay(
                columns=["is_conscious"],
                output_name="was_conscious",
            )
        )

    if not aggregation_expressions:
        # Preserve the patient identifier dtype and return one row per patient.
        return dataframe.select(patient_col).unique(maintain_order=True)

    flags = (
        dataframe
        .group_by(patient_col, maintain_order=True)
        .agg(aggregation_expressions)
    )

    expected_patients = dataframe[patient_col].n_unique()
    if flags.height != expected_patients:
        raise RuntimeError(
            "Patient-level flag aggregation produced an unexpected number "
            f"of rows: expected {expected_patients}, got {flags.height}."
        )

    if "had_ventilation" in flags.columns:
        ventilation_count = (
            flags
            .select(pl.col("had_ventilation").sum())
            .item()
        )
        print(
            "[TABLEONE] had_ventilation=True for "
            f"{int(ventilation_count)} / {flags.height} patient(s).",
            flush=True,
        )

    return flags


def _translate_tableone_categories(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Translate and normalize original categorical values for TableOne.

    The modelling dataframe contains translated dummy-column names, but the
    descriptive table merges the original categorical columns back in. Their
    values therefore need to be translated separately before TableOne is run.
    """
    translated = dataframe.copy()

    if "gender" in translated.columns:
        translated["gender"] = (
            translated["gender"]
            .map(
                lambda value: (
                    FR_TO_EN.get(str(value), str(value))
                    if pd.notna(value)
                    else "Unknown"
                )
            )
            .replace({"nan": "Unknown", "None": "Unknown"})
        )

    if "icu_mode_entree" in translated.columns:
        translated["icu_mode_entree"] = translated["icu_mode_entree"].map(
            lambda value: (
                ENTRY_MODE_TO_LABEL.get(str(value), "Others")
                if pd.notna(value)
                else "Others"
            )
        )

    return translated


def _find_binary_indicator_features(
    dataframe: pd.DataFrame,
    categorical_features: Sequence[str],
) -> list[str]:
    """Return categorical variables whose observed values are exactly 0 and 1."""
    binary_features: list[str] = []

    for feature in categorical_features:
        if feature not in dataframe.columns:
            continue

        numeric_values = pd.to_numeric(
            dataframe[feature].dropna(),
            errors="coerce",
        ).dropna()

        unique_values = set(numeric_values.unique().tolist())
        if unique_values == {0, 1} or unique_values == {0.0, 1.0}:
            binary_features.append(feature)

    return binary_features


def _keep_positive_level_for_binary_features(
    table_dataframe: pd.DataFrame,
    binary_features: Sequence[str],
) -> pd.DataFrame:
    """Keep only the positive level for categorical 0/1 indicators.

    Non-binary categorical variables such as gender keep all their levels.
    """
    if not binary_features:
        return table_dataframe.copy()

    if (
        not isinstance(table_dataframe.index, pd.MultiIndex)
        or table_dataframe.index.nlevels != 2
    ):
        raise ValueError(
            "The TableOne result must have a two-level MultiIndex."
        )

    result = table_dataframe.copy()
    first_level = result.index.get_level_values(0).astype(str)
    second_level = result.index.get_level_values(1).astype(str)

    # TableOne normally repeats the variable name on every category row, but
    # forward filling also supports versions that leave repeated labels blank.
    current_feature = ""
    row_features: list[str] = []
    for raw_label in first_level:
        label = raw_label.strip()
        if label and label.lower() not in {"nan", "none"}:
            current_feature = label.split(",", maxsplit=1)[0].strip()
        row_features.append(current_feature)

    positive_levels = {"1", "1.0", "true"}
    keep_mask: list[bool] = []

    binary_set = set(binary_features)
    for feature, level in zip(row_features, second_level, strict=True):
        if feature not in binary_set:
            keep_mask.append(True)
            continue

        normalized_level = level.strip().lower()
        keep_mask.append(normalized_level in positive_levels)

    filtered = result.loc[keep_mask]

    print(
        "[TABLEONE] Binary indicators displayed with positive level only: "
        f"{sorted(binary_features)}",
        flush=True,
    )
    return filtered

def build_tableone(
    df_clean: pl.DataFrame,
    categorical_data: pl.DataFrame,
    patient_col: str,
    target_col: str,
    final_features: list[str],
    generated_dummy_columns: list[str],
    categorical_source_columns: list[str],
    config_mode_name: str,
    output_dir: Path,
) -> TableOne:
    """Build and export a cohort TableOne with explicit variable sections.

    The input dataframe is reduced to one observation per patient. Original
    categorical columns are merged back after one-hot encoded columns are
    removed. The exported table separates continuous and categorical
    variables into visually distinct sections.

    Args:
        df_clean: Fully preprocessed dataframe, potentially containing several
            rows per patient.
        categorical_data: Original categorical variables collected before
            one-hot encoding.
        patient_col: Patient identifier column.
        target_col: Binary outcome column.
        final_features: Features retained after preprocessing.
        generated_dummy_columns: Dummy columns generated during categorical
            encoding.
        categorical_source_columns: Original categorical variables to display
            in the descriptive table.
        config_mode_name: Windowing or resampling configuration name.
        output_dir: Directory in which the table files are written.

    Returns:
        The original TableOne object containing the computed statistics.
        The exported HTML, CSV, and LaTeX files contain the additional
        continuous and categorical section headers.

    Raises:
        ValueError: If no static feature is available for description.
    """
    selected_columns = list(
        dict.fromkeys(
            [
                patient_col,
                target_col,
                *final_features,
            ]
        )
    )

    # Compute one boolean value per patient from the complete stay.
    # For had_ventilation this means:
    #   any source column is True on any row of the stay.
    flags_df = _build_patient_level_clinical_flags(
        dataframe=df_clean,
        patient_col=patient_col,
    )

    df_static = (
        df_clean
        .select(selected_columns)
        .unique(subset=[patient_col], keep="first")
    )

    static_features = build_static_feature_list(
        dataframe=df_static,
        generated_dummy_columns=generated_dummy_columns,
        config_mode_name=config_mode_name,
        final_features=final_features,
    )

    pd_static = df_static.to_pandas()

    # Keep GHM and entry mode dummy columns for TableOne; drop only others
    keep_for_tableone = {
        col for col in generated_dummy_columns
        if col.startswith("icu_ghm_") or col.startswith("icu_mode_entree_")
    }
    drop_columns = [
        col
        for col in generated_dummy_columns
        if col in pd_static.columns and col not in keep_for_tableone
    ]
    pd_static = pd_static.drop(columns=drop_columns)

    pd_categorical = (
        categorical_data
        .unique(subset=[patient_col], keep="first")
        .to_pandas()
    )

    pd_static = pd_static.merge(
        pd_categorical,
        on=patient_col,
        how="left",
        suffixes=("", "_categorical"),
    )

    # The original categorical values are merged back for TableOne, so their
    # values must be translated independently from the model dummy columns.
    pd_static = _translate_tableone_categories(pd_static)

    # Drop columns that contain array/list values (e.g. icu_ghm as a list).
    # TableOne's pd.isnull() fails on cell values that are arrays.
    for col in pd_static.columns:
        sample = pd_static[col].dropna().iloc[0:1]
        if len(sample) > 0 and isinstance(sample.iloc[0], (list, np.ndarray, pl.Series)):
            pd_static = pd_static.drop(columns=[col])

    # Merge patient-level flags (convert bool to int for TableOne compat)
    if not flags_df.is_empty():
        pd_flags = flags_df.to_pandas()
        for flag_col in pd_flags.columns:
            if flag_col != patient_col and pd.api.types.is_bool_dtype(
                pd_flags[flag_col]
            ):
                pd_flags[flag_col] = pd_flags[flag_col].astype(int)
        pd_static = pd_static.merge(
            pd_flags,
            on=patient_col,
            how="left",
        )

    continuous_features = [
        feature
        for feature in [
            "age",
            "score_glasgow",
            "real_time_hours",
            "observed_duration",
        ]
        if feature in static_features
        and feature in pd_static.columns
    ]

    for feature in continuous_features:
        pd_static[feature] = pd.to_numeric(
            pd_static[feature],
            errors="coerce",
        )

    categorical_features = [
        feature
        for feature in categorical_source_columns
        if feature in pd_static.columns
        and feature not in continuous_features
    ]

    for feature in ["gender", target_col]:
        if (
            feature in pd_static.columns
            and feature not in categorical_features
            and feature not in continuous_features
        ):
            categorical_features.append(feature)

    # Add patient-level clinical flags as categorical variables
    clinical_flags = ["had_ventilation", "had_nad", "was_conscious"]
    for flag in clinical_flags:
        if (
            flag in pd_static.columns
            and flag not in categorical_features
            and flag not in continuous_features
        ):
            categorical_features.append(flag)

    # Add GHM and entry mode dummy columns as categorical variables
    for col in keep_for_tableone:
        if (
            col in pd_static.columns
            and col not in categorical_features
            and col not in continuous_features
        ):
            categorical_features.append(col)

    describe_columns = [
        *continuous_features,
        *categorical_features,
    ]
    describe_columns = list(dict.fromkeys(describe_columns))

    if not describe_columns:
        raise ValueError(
            "No static features are available for the descriptive table."
        )

    # Identify only genuine 0/1 indicators. Multi-level categorical variables
    # such as gender and entry mode keep all their categories.
    binary_indicator_features = _find_binary_indicator_features(
        dataframe=pd_static,
        categorical_features=categorical_features,
    )

    # Ensure ALL columns in pd_static are simple scalar types for TableOne.
    # TableOne's pd.isnull() fails on array-like or boolean dtypes.
    for col in pd_static.columns:
        if pd.api.types.is_bool_dtype(pd_static[col]):
            pd_static[col] = pd_static[col].astype(int)
        elif pd.api.types.is_numeric_dtype(pd_static[col]):
            # Keep numeric as-is (already handled for continuous features)
            pass
        else:
            pd_static[col] = pd_static[col].astype(str)

    table = TableOne(
        data=pd_static,
        columns=describe_columns,
        categorical=categorical_features,
        continuous=continuous_features,
        pval=False,
        decimals=2,
        missing=False,
    )

    positive_binary_table = _keep_positive_level_for_binary_features(
        table_dataframe=table.tableone,
        binary_features=binary_indicator_features,
    )

    formatted_table = add_variable_type_sections(
        table_dataframe=positive_binary_table,
        continuous_features=continuous_features,
        categorical_features=categorical_features,
    )

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    formatted_table.to_html(
        output_dir / "tableone_static_features.html",
    )
    formatted_table.to_csv(
        output_dir / "tableone_static_features.csv",
    )
    formatted_table.to_latex(
        output_dir / "tableone_static_features.tex",
    )

    return table