"""Static feature extraction and baseline statistics utilities.

Provides functions to compute static (patient-level) features from
ICU time-series data, including demographic information, admission
characteristics, and baseline laboratory values. Also generates Table 1
summary statistics using the TableOne library.
"""

from collections.abc import Sequence
from pathlib import Path
import re

import numpy as np
import pandas as pd
import polars as pl
import polars.selectors as cs
from tableone import TableOne


GHM_CODE_TO_LABEL_FR: dict[str, str] = {
    "01C": "neurochirurgie",
    "01M": "neurologie",
    "01K": "Embolisation cerebrales ou medullaire",
    "03C": "chirurgie ORL",
    "04M": "Pathologie Respiratoire",
    "05C": "Chirurgie cardio-vasculaire (hors endoprothese)",
    "05K": "Endoprothese vasculaire",
    "05M": "Cardiologie",
    "06M": "Atteinte digestive",
    "07M": "Atteinte hépatobiliaire et pancréatique",
    "08C": "Chirurgie Orthopédique et Amputations",
    "10M": "Diabete et troubles metaboliques",
    "11C": "Chirurgie Urologique",
    "11M": "Pyelonéphrite non chirurgicale et insuffisance rénale",
    "18M": "Maladie infectieuse et sepsis without precision",
    "21M": "Intoxication",
    "26C": "Polytraumatisme",
    "26M": "Polytraumatisme",
    "27C": "Transplantation organe solide",
}

GHM_CODE_TO_LABEL: dict[str, str] = {
    "01C": "Neurosurgery and neuro-embolisation",
    "01M": "Neurology",
    "01K": "Neurosurgery and neuro-embolisation",
    "03C": "ENT Surgery",
    "04M": "Respiratory Pathology",
    "05C": "Cardiovascular Surgery",
    "05K": "Cardiovascular Surgery",
    "05M": "Cardiology",
    "06M": "Gastroenterology",
    "07M": "Gastroenterology",
    "08C": "Orthopedic Surgery and Amputations",
    "10M": "Metabolic and renal disorders",
    "11C": "Urological Surgery",
    "11M": "Metabolic and renal disorders",
    "18M": "Infectious Disease and Sepsis",
    "21M": "Poisoning",
    "26C": "Polytrauma",
    "26M": "Polytrauma",
    "27C": "Solid Organ Transplantation",
}


ENTRY_MODE_TO_LABEL: dict[str, str] = {
    "Domicile": "Home or Emergency",
    "Urgence": "Home or Emergency",
    "Transfert MCO": "Hospital Transfer",
    "Mutation MCO": "Inter-hospital Transfer",
}


FR_TO_EN: dict[str, str] = {
    # Gender
    "Féminin": "Female",
    "Masculin": "Male",
}


# Display names for TableOne only. Column names in the modelling pipeline
# remain unchanged; this mapping is applied temporarily before TableOne
# generation and affects the exported HTML/CSV/LaTeX output.
TABLEONE_COLUMN_DISPLAY_NAMES: dict[str, str] = {
    "age": "Age",
    "score_glasgow": "Glasgow Score",
    "icu_ghm": "ICU Disease Group",
    "icu_mode_entree": "ICU Entry Mode",
    "admission_type": "Admission Type",
    "gender": "Gender",
    "had_dialyse": "Dialysis",
    "had_vasoactive_drugs": "Vasoactive Drugs",
    "was_conscious": "Conscious",
    "was_ventilated": "Ventilated",
    "real_time_hours": "Real Time (hours)",
    "observed_duration": "Observed Duration",
    # Target columns (mortality outcomes)
    "isDeceased_lt_28d": "28-Day Mortality",
}


def _get_entry_mode_label(mode: str) -> str:
    """Map a raw ICU entry mode to a grouped, human-readable label.

    Args:
        mode: Raw entry mode value from the dataset.

    Returns:
        The grouped label for the entry mode.
    """
    return ENTRY_MODE_TO_LABEL.get(mode, "Others")


def rename_ghm_dummies(columns: list[str]) -> dict[str, str]:
    """Rename GHM dummy columns to human-readable ICU_ghm labels.

    Each dummy column produced by Polars (e.g. ``icu_ghm_f3_01C``) is
    mapped to a readable name following the pattern ``icu_ghm_<label>``.
    Codes that are not explicitly defined fall back to ``icu_ghm_Others``.

    Args:
        columns: GHM dummy column names generated by ``to_dummies``
            (e.g. ``["icu_ghm_f3_01C", "icu_ghm_f3_21M"]``).

    Returns:
        Dictionary mapping original dummy column names to their readable
        counterparts. Only columns whose name starts with ``icu_ghm_f3_``
        are included.

    Examples:
        >>> rename_ghm_dummies(["icu_ghm_f3_01C", "icu_ghm_f3_99Z"])
        {
            "icu_ghm_f3_01C": "icu_ghm_neurochirurgie",
            "icu_ghm_f3_99Z": "icu_ghm_Others",
        }
    """
    result: dict[str, str] = {}

    for column in columns:
        if not column.startswith("icu_ghm_f3_"):
            continue

        code = column.removeprefix("icu_ghm_f3_")
        label = GHM_CODE_TO_LABEL.get(code, "Others")
        result[column] = f"icu_ghm_{label}"

    return result


def encode_categorical_features(
    dataframe: pl.DataFrame,
    feature_mode: str,
    features_to_keep: Sequence[str],
) -> tuple[pl.DataFrame, list[str], list[str]]:
    """Encode categorical model features.

    Admission type is always one-hot encoded. GHM prefixes and ICU entry
    modes are encoded in ``Mode Commonly Used``. Gender is encoded in the
    custom and complete feature modes.

    Args:
        dataframe: Input patient time-series dataframe.
        feature_mode: Selected feature configuration.
        features_to_keep: Features selected before categorical encoding.

    Returns:
        A tuple containing:
            - The transformed dataframe.
            - The updated feature list.
            - The names of all generated dummy columns.
    """
    processed_dataframe = dataframe
    updated_features = list(features_to_keep)
    generated_dummy_columns: list[str] = []

    processed_dataframe = (
        processed_dataframe
        .with_columns(
            pl.col("admission_type").fill_null("Unknown"),
        )
        .to_dummies(columns=["admission_type"])
    )

    admission_dummy_columns = [
        column
        for column in processed_dataframe.columns
        if column.startswith("admission_type_")
    ]
    generated_dummy_columns.extend(admission_dummy_columns)

    if "admission_type" in updated_features:
        updated_features.remove("admission_type")
        updated_features.extend(admission_dummy_columns)

    if feature_mode == "Mode Commonly Used":
        processed_dataframe = processed_dataframe.with_columns(
            pl.col("icu_ghm")
            .list.first()
            .cast(pl.String)
            .str.head(3)
            .fill_null("Unknown")
            .alias("icu_ghm_f3"),
        )

        ghm_dummies = (
            processed_dataframe
            .select("icu_ghm_f3")
            .to_dummies(columns=["icu_ghm_f3"])
        )

        unknown_ghm_column = "icu_ghm_f3_Unknown"
        if unknown_ghm_column in ghm_dummies.columns:
            ghm_dummies = ghm_dummies.drop(unknown_ghm_column)

        # Rename GHM dummy columns to human-readable labels (merge duplicates)
        ghm_rename_mapping = rename_ghm_dummies(ghm_dummies.columns)

        # Group columns by target name so duplicates are summed rather than
        # causing a Polars DuplicateError.
        target_groups: dict[str, list[str]] = {}
        for original, target in ghm_rename_mapping.items():
            target_groups.setdefault(target, []).append(original)

        merged_columns: list[pl.Expr] = []
        for target, sources in target_groups.items():
            if len(sources) == 1:
                merged_columns.append(pl.col(sources[0]).alias(target))
            else:
                merged_columns.append(
                    pl.sum_horizontal(*sources).alias(target)
                )

        ghm_dummies = ghm_dummies.select(merged_columns)

        # Map entry modes to grouped labels (nulls and unknown values -> Other)
        processed_dataframe = processed_dataframe.with_columns(
            pl.col("icu_mode_entree")
            .fill_null("Others")
            .replace_strict(
                {k: v for k, v in ENTRY_MODE_TO_LABEL.items()},
                default="Others",
                return_dtype=pl.String,
            )
            .alias("icu_mode_entree_label")
        )

        entry_mode_dummies = (
            processed_dataframe
            .select("icu_mode_entree_label")
            .to_dummies(columns=["icu_mode_entree_label"])
        )

        # Rename entry mode dummy columns to icu_mode_entree_<label>
        entry_rename_mapping = {
            f"icu_mode_entree_label_{label}": f"icu_mode_entree_{label}"
            for label in ["Home or Emergency", "Hospital Transfer", "Inter-hospital Transfer", "Others"]
        }
        entry_mode_dummies = entry_mode_dummies.rename(
            {k: v for k, v in entry_rename_mapping.items() if k in entry_mode_dummies.columns}
        )

        new_dummy_columns = [
            *ghm_dummies.columns,
            *entry_mode_dummies.columns,
        ]
        generated_dummy_columns.extend(new_dummy_columns)

        source_columns = {
            "icu_ghm",
            "icu_ghm_f3",
            "icu_mode_entree",
            "icu_mode_entree_label",
        }

        updated_features = [
            feature
            for feature in updated_features
            if feature not in source_columns
        ]
        updated_features.extend(new_dummy_columns)

        existing_source_columns = [
            column
            for column in source_columns
            if column in processed_dataframe.columns
        ]

        processed_dataframe = pl.concat(
            [
                processed_dataframe.drop(existing_source_columns),
                ghm_dummies,
                entry_mode_dummies,
            ],
            how="horizontal",
        )

    gender_feature_modes = {
        "Mode Custom",
        "Mode All Without pmsi",
        "Mode All",
    }

    if feature_mode in gender_feature_modes:
        processed_dataframe = (
            processed_dataframe
            .with_columns(
                pl.col("gender").fill_null("Unknown"),
            )
            .to_dummies(columns=["gender"])
        )

        gender_dummy_columns = [
            column
            for column in processed_dataframe.columns
            if column.startswith("gender_")
        ]
        generated_dummy_columns.extend(gender_dummy_columns)

        # Rename gender dummy columns using FR_TO_EN mapping
        gender_rename_mapping: dict[str, str] = {}
        for col in gender_dummy_columns:
            value = col.removeprefix("gender_")
            if value in FR_TO_EN:
                gender_rename_mapping[col] = f"gender_{FR_TO_EN[value]}"
        if gender_rename_mapping:
            processed_dataframe = processed_dataframe.rename(gender_rename_mapping)
            generated_dummy_columns = [
                gender_rename_mapping.get(col, col)
                for col in generated_dummy_columns
            ]
            if "gender" in updated_features:
                updated_features.remove("gender")
                updated_features.extend(generated_dummy_columns)
            else:
                updated_features = [
                    gender_rename_mapping.get(f, f) for f in updated_features
                ]
        else:
            if "gender" in updated_features:
                updated_features.remove("gender")
                updated_features.extend(gender_dummy_columns)

    processed_dataframe = processed_dataframe.with_columns(
        cs.numeric().cast(pl.Float64),
        cs.boolean().cast(pl.Float64),
    )

    return (
        processed_dataframe,
        list(dict.fromkeys(updated_features)),
        list(dict.fromkeys(generated_dummy_columns)),
    )


def build_static_feature_list(
    dataframe: pl.DataFrame,
    generated_dummy_columns: Sequence[str],
    config_mode_name: str,
    final_features: Sequence[str] | None = None,
) -> list[str]:
    """Build the list of patient-level static features.

    Static features are excluded from time-series feature extraction and are
    described directly in the cohort summary table.

    Args:
        dataframe: Fully preprocessed time-series dataframe.
        generated_dummy_columns: Dummy columns created during categorical
            encoding.
        config_mode_name: Windowing or resampling configuration name.
        final_features: Optional final feature list used to filter the result.

    Returns:
        Static feature names available in the requested feature set.

    Raises:
        ValueError: If an expected static feature is absent from the dataframe
            when no final feature list is provided.
    """
    static_features = [
        *generated_dummy_columns,
        "age",
        "score_glasgow",
    ]

    # Include any column matching the "hx_" prefix (comorbidities).
    _hx_pattern = re.compile(r"^hx_")
    static_features.extend(
        column
        for column in dataframe.columns
        if _hx_pattern.match(column)
    )

    if config_mode_name == "resampling_X_points":
        static_features.append("real_time_hours")
    elif (
        config_mode_name
        == "resampling_x_points_alea_lomax_prio_24h_no-fill"
    ):
        static_features.append("observed_duration")

    static_features = list(dict.fromkeys(static_features))

    if final_features is not None:
        return [
            feature
            for feature in static_features
            if feature in final_features
        ]

    missing_features = [
        feature
        for feature in static_features
        if feature not in dataframe.columns
    ]

    if missing_features:
        raise ValueError(
            "Static features are missing from the preprocessed dataframe: "
            f"{missing_features}"
        )

    return static_features


def add_variable_type_sections(
    table_dataframe: pd.DataFrame,
    continuous_features: Sequence[str],
    categorical_features: Sequence[str],
) -> pd.DataFrame:
    """Add continuous and categorical section headers to a TableOne result.

    The summary statistics are left unchanged. Only the row layout is
    reorganized to make the distinction between continuous and categorical
    variables explicit.

    Args:
        table_dataframe: DataFrame produced by ``TableOne.tableone``.
        continuous_features: Variables displayed as continuous.
        categorical_features: Variables displayed as categorical.

    Returns:
        A copy of the TableOne dataframe containing explicit section rows.

    Raises:
        ValueError: If the TableOne dataframe does not use the expected
            two-level row index.
    """
    if (
        not isinstance(table_dataframe.index, pd.MultiIndex)
        or table_dataframe.index.nlevels != 2
    ):
        raise ValueError(
            "The TableOne result must have a two-level MultiIndex."
        )

    table_dataframe = table_dataframe.copy()
    first_index_level = (
        table_dataframe.index
        .get_level_values(0)
        .astype(str)
    )

    def create_section_row(title: str) -> pd.DataFrame:
        """Create an empty row used as a section header."""
        section_index = pd.MultiIndex.from_tuples(
            [(title, "")],
            names=table_dataframe.index.names,
        )

        return pd.DataFrame(
            "",
            index=section_index,
            columns=table_dataframe.columns,
        )

    def select_feature_rows(features: Sequence[str]) -> list[pd.DataFrame]:
        """Select complete TableOne row blocks for the requested features."""
        selected_blocks: list[pd.DataFrame] = []

        for feature in features:
            pattern = rf"^{re.escape(feature)}(?:,|$)"
            matching_rows = first_index_level.str.match(pattern)

            if matching_rows.any():
                selected_blocks.append(table_dataframe.loc[matching_rows])

        return selected_blocks

    output_blocks: list[pd.DataFrame] = []

    sample_size_rows = first_index_level == "n"
    if sample_size_rows.any():
        output_blocks.append(table_dataframe.loc[sample_size_rows])

    continuous_blocks = select_feature_rows(continuous_features)
    if continuous_blocks:
        output_blocks.append(create_section_row("Continuous variables"))
        output_blocks.extend(continuous_blocks)

    categorical_blocks = select_feature_rows(categorical_features)
    if categorical_blocks:
        output_blocks.append(create_section_row("Categorical variables"))
        output_blocks.extend(categorical_blocks)

    return pd.concat(output_blocks)



def _any_boolean_during_stay(
    columns: Sequence[str],
    output_name: str,
    check_any_false: bool = False,
) -> pl.Expr:
    """Return whether any input flag is true (or false) at least once during a stay.

    The expression first combines the requested columns row by row, then
    aggregates the resulting boolean values over every row of the patient
    group. When ``check_any_false`` is ``False`` (default), null and non-convertible
    values are treated as ``False``. When ``True``, they are treated as ``True``.

    Args:
        columns:
            Boolean-like columns to inspect.
        output_name:
            Name assigned to the resulting patient-level flag.
        check_any_false:
            If ``False``, returns ``True`` when at least one column is ``True``
            on any row of the stay. If ``True``, returns ``True`` when at least
            one column is ``False`` on any row of the stay.

    Returns:
        A Polars aggregation expression yielding one boolean per patient.
    """
    if not columns:
        raise ValueError(
            f"At least one source column is required for {output_name!r}."
        )

    casted_columns = [
        pl.col(column).cast(pl.Boolean, strict=False)
        for column in columns
    ]

    if check_any_false:
        # Treat nulls as True; detect any False via negated all_horizontal.
        row_has_false = pl.all_horizontal(
            [col.fill_null(True) for col in casted_columns]
        ).not_()
        return row_has_false.any().alias(output_name)

    row_has_true = pl.any_horizontal(
        [col.fill_null(False) for col in casted_columns]
    )
    return row_has_true.any().alias(output_name)


def _build_patient_level_clinical_flags(
    dataframe: pl.DataFrame,
    patient_col: str,
) -> pl.DataFrame:
    """Build one row of clinical history flags per patient.

    ``had_dialyse`` is true when at least one ventilation source column
    is true on at least one row of the patient's stay.
    """
    aggregation_expressions: list[pl.Expr] = []

    dialyse_columns = [
        column
        for column in ("is_cvvhf", "is_hdi")
        if column in dataframe.columns
    ]

    vaso_active_columns = [
        column
        for column in ("nad_dose_poids", "dobu_dose_poids")
        if column in dataframe.columns
    ]

    if dialyse_columns:
        aggregation_expressions.append(
            _any_boolean_during_stay(
                columns=dialyse_columns,
                output_name="had_dialyse",
            )
        )

    if vaso_active_columns:
        # Build per-column expressions: is any value != 0?
        vaso_exprs = [
            pl.col(col).ne(0).any() for col in vaso_active_columns
        ]
        aggregation_expressions.append(
            pl.any_horizontal(*vaso_exprs).alias("had_vasoactive_drugs")
        )

    if "is_conscious" in dataframe.columns:
        aggregation_expressions.append(
            _any_boolean_during_stay(
                columns=["is_conscious"],
                output_name="was_conscious",
                check_any_false = False
            )
        )
    if "is_ventilated" in dataframe.columns:
        aggregation_expressions.append(
            _any_boolean_during_stay(
                columns=["is_ventilated"],
                output_name="was_ventilated",
            )
        )

    if not aggregation_expressions:
        # Preserve the patient identifier dtype and return one row per patient.
        return dataframe.select(patient_col).unique(maintain_order=True)

    flags = (
        dataframe
        .group_by(patient_col, maintain_order=True)
        .agg(aggregation_expressions)
    )

    expected_patients = dataframe[patient_col].n_unique()
    if flags.height != expected_patients:
        raise RuntimeError(
            "Patient-level flag aggregation produced an unexpected number "
            f"of rows: expected {expected_patients}, got {flags.height}."
        )

    if "had_dialyse" in flags.columns:
        ventilation_count = (
            flags
            .select(pl.col("had_dialyse").sum())
            .item()
        )
        print(
            "[TABLEONE] had_dialyse=True for "
            f"{int(ventilation_count)} / {flags.height} patient(s).",
            flush=True,
        )

    return flags


def _translate_tableone_categories(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """Translate and normalize original categorical values for TableOne.

    The modelling dataframe contains translated dummy-column names, but the
    descriptive table merges the original categorical columns back in. Their
    values therefore need to be translated separately before TableOne is run.
    """
    translated = dataframe.copy()

    if "gender" in translated.columns:
        translated["gender"] = (
            translated["gender"]
            .map(
                lambda value: (
                    FR_TO_EN.get(str(value), str(value))
                    if pd.notna(value)
                    else "Unknown"
                )
            )
            .replace({"nan": "Unknown", "None": "Unknown"})
        )

    if "icu_mode_entree" in translated.columns:
        translated["icu_mode_entree"] = translated["icu_mode_entree"].map(
            lambda value: (
                ENTRY_MODE_TO_LABEL.get(str(value), "Others")
                if pd.notna(value)
                else "Others"
            )
        )

    return translated


def _dedummy_categorical_columns(
    dataframe: pd.DataFrame,
    prefix: str,
    output_column: str,
    reverse_label_map: dict[str, str] | None = None,
) -> pd.DataFrame:
    """Reverse one-hot encoding for a group of dummy columns.

    For each row, the column with value ``1`` determines the categorical
    label stored in the output column. Rows where no dummy is active or
    where multiple dummies are active receive ``"Unknown"``.

    Args:
        dataframe: Input DataFrame containing the dummy columns.
        prefix: Column name prefix to identify the dummy group
            (e.g. ``"icu_ghm_"``).
        output_column: Name of the reconstructed categorical column
            (e.g. ``"icu_ghm"``).
        reverse_label_map: Optional mapping from dummy-label to a
            display-friendly label. When ``None``, the label embedded in
            the column name is used as-is.

    Returns:
        A copy of the DataFrame with the dummy columns removed and the
        new categorical column added.
    """
    result = dataframe.copy()
    dummy_columns = [
        col for col in result.columns
        if col.startswith(prefix) and col != output_column
    ]

    if not dummy_columns:
        return result

    # Build mapping: dummy column name -> categorical label
    label_map: dict[str, str] = {}
    for col in dummy_columns:
        raw_label = col.removeprefix(prefix)
        label = (
            reverse_label_map.get(raw_label, raw_label)
            if reverse_label_map is not None
            else raw_label
        )
        label_map[col] = label

    # Reconstruct categorical value row by row.
    # When no dummy is active (or multiple are active), merge into "Others"
    # rather than creating a separate "Unknown" category.
    def _resolve_label(row: pd.Series) -> str:
        active_columns = [
            col for col in dummy_columns
            if pd.notna(row.get(col)) and row[col] == 1
        ]
        if len(active_columns) == 1:
            return label_map[active_columns[0]]
        return "Others"

    result[output_column] = result.apply(_resolve_label, axis=1)

    # Drop the original dummy columns
    result = result.drop(columns=dummy_columns)

    return result


def _sort_categorical_rows_by_frequency(
    table_dataframe: pd.DataFrame,
    features_to_sort: Sequence[str],
) -> pd.DataFrame:
    """Sort category rows within the specified features by descending count.

    For each feature listed in ``features_to_sort``, the category sub-rows
    are reordered by the count extracted from the "Overall" column (format
    ``"n (pct)"`` or plain numeric) in descending order. Section header rows
    and non-target features are untouched.

    Args:
        table_dataframe: The formatted TableOne dataframe (two-level
            MultiIndex).
        features_to_sort: Feature display names whose category rows should
            be sorted by frequency.

    Returns:
        The dataframe with the requested feature rows reordered.
    """
    if (
        not isinstance(table_dataframe.index, pd.MultiIndex)
        or table_dataframe.index.nlevels != 2
    ):
        return table_dataframe

    result = table_dataframe.copy()
    first_level = result.index.get_level_values(0).astype(str)
    features_set = set(features_to_sort)

    # TableOne stores the Overall column as strings like "8466 (52.07)".
    # Extract the raw count for numeric sorting.
    overall_col = "Overall" if "Overall" in result.columns else result.columns[-1]

    def _extract_count(value: object) -> float:
        """Parse count from TableOne cell values such as '8466 (52.07)'."""
        if pd.isna(value):
            return 0.0
        text = str(value).strip()
        # Try plain numeric first
        try:
            return float(text)
        except ValueError:
            pass
        # Try "n (pct)" pattern
        match = re.match(r"^([0-9]+(?:,[0-9]+)?(?:\.[0-9]+)?)\s*\(", text)
        if match:
            return float(match.group(1).replace(",", ""))
        return 0.0

    output_blocks: list[pd.DataFrame] = []
    i = 0

    while i < len(result):
        row_label = first_level[i].strip()

        # TableOne index includes ", n (%)" suffix; match by prefix
        matching_feature = None
        for feat in features_set:
            if row_label.startswith(feat):
                matching_feature = feat
                break

        if matching_feature is not None:
            # Collect all consecutive rows for this feature
            feature_rows_indices: list[int] = []
            j = i
            while j < len(result):
                if first_level[j].strip().startswith(matching_feature):
                    feature_rows_indices.append(j)
                    j += 1
                else:
                    break

            # Sort these rows by extracted count descending
            feature_df = result.iloc[feature_rows_indices].copy()
            feature_df["_sort_key"] = feature_df[overall_col].apply(_extract_count)
            sorted_df = feature_df.sort_values("_sort_key", ascending=False).drop(
                columns=["_sort_key"]
            )
            output_blocks.append(sorted_df)
            i = j
        else:
            output_blocks.append(result.iloc[i:i + 1])
            i += 1

    return pd.concat(output_blocks)


def _find_binary_indicator_features(
    dataframe: pd.DataFrame,
    categorical_features: Sequence[str],
) -> list[str]:
    """Return categorical variables whose observed values are exactly 0 and 1."""
    binary_features: list[str] = []

    for feature in categorical_features:
        if feature not in dataframe.columns:
            continue

        numeric_values = pd.to_numeric(
            dataframe[feature].dropna(),
            errors="coerce",
        ).dropna()

        unique_values = set(numeric_values.unique().tolist())
        if unique_values == {0, 1} or unique_values == {0.0, 1.0}:
            binary_features.append(feature)

    return binary_features


def _keep_positive_level_for_binary_features(
    table_dataframe: pd.DataFrame,
    binary_features: Sequence[str],
) -> pd.DataFrame:
    """Keep only the positive level for categorical 0/1 indicators.

    Non-binary categorical variables such as gender keep all their levels.
    """
    if not binary_features:
        return table_dataframe.copy()

    if (
        not isinstance(table_dataframe.index, pd.MultiIndex)
        or table_dataframe.index.nlevels != 2
    ):
        raise ValueError(
            "The TableOne result must have a two-level MultiIndex."
        )

    result = table_dataframe.copy()
    first_level = result.index.get_level_values(0).astype(str)
    second_level = result.index.get_level_values(1).astype(str)

    # TableOne normally repeats the variable name on every category row, but
    # forward filling also supports versions that leave repeated labels blank.
    current_feature = ""
    row_features: list[str] = []
    for raw_label in first_level:
        label = raw_label.strip()
        if label and label.lower() not in {"nan", "none"}:
            current_feature = label.split(",", maxsplit=1)[0].strip()
        row_features.append(current_feature)

    positive_levels = {"1", "1.0", "true"}
    keep_mask: list[bool] = []

    binary_set = set(binary_features)
    for feature, level in zip(row_features, second_level, strict=True):
        if feature not in binary_set:
            keep_mask.append(True)
            continue

        normalized_level = level.strip().lower()
        keep_mask.append(normalized_level in positive_levels)

    filtered = result.loc[keep_mask]

    print(
        "[TABLEONE] Binary indicators displayed with positive level only: "
        f"{sorted(binary_features)}",
        flush=True,
    )
    return filtered

from pathlib import Path
import numpy as np
import pandas as pd
import polars as pl
from tableone import TableOne


from pathlib import Path
import numpy as np
import pandas as pd
import polars as pl
from tableone import TableOne


def build_tableone(
    df_clean: pl.DataFrame,
    df_static_source: pl.DataFrame,  # <-- NOUVEAU PARAMÈTRE
    categorical_data: pl.DataFrame,
    patient_col: str,  # Ex: "encounterId"
    target_col: str,
    final_features: list[str],
    generated_dummy_columns: list[str],
    categorical_source_columns: list[str],
    config_mode_name: str,
    output_dir: Path,
    top_n_ghm: int | None = 5,
) -> TableOne:
    
    # -------------------------------------------------------------------------
    # 0. MERGE DES DATASETS ET CALCUL DU FLAG SEPSIS (Polars)
    # -------------------------------------------------------------------------
    df_clean = df_clean.with_columns(pl.col("encounterId").cast(pl.Int64))
    df_static_source = df_static_source.with_columns(pl.col("encounterId").cast(pl.Int64))
    # Récupération de 'los', 'icu_DA', 'icu_DP_code' via Inner Merge sur patient_col (encounterId)
    required_cols = [patient_col, "los", "icu_DA", "icu_DP_code", "sapsii"]
    
    # Sélection proactive des colonnes utiles du dataset source pour éviter les doublons
    static_to_merge = df_static_source.select(
        [c for c in required_cols if c in df_static_source.columns]
    )

    df_clean = df_clean.join(
        static_to_merge,
        on=patient_col,
        how="inner"
    )

    codes_cim = [
        "R57.2", "R65.1", "A02.1", "A22.7", "A26.7", "A32.7", "A42.7",
        "B37.7", "O85", "A40.0", "A40.1", "A40.2", "A40.3", "A40.8",
        "A40.9", "A41.0", "A41.1", "A41.2", "A41.3", "A41.4", "A41.5",
        "A41.8", "A41.9", "P36.00", "P36.10", "P36.20", "P36.30", "P36.40",
        "P36.50", "P36.90",
    ]

    # Construction de la colonne Sepsis au niveau patient
    sepsis_df = (
        df_clean.group_by(patient_col).agg(
            (
                pl.col("icu_DA")
                .list.eval(pl.element().is_in(codes_cim))
                .list.any()
                | pl.col("icu_DP_code").is_in(codes_cim)
            )
            .any()
            .cast(pl.Int8)
            .alias("sepsis")
        )
    )

    selected_columns = list(
        dict.fromkeys(
            [
                patient_col,
                target_col,
                *final_features,
                "sapsii", 
                "los", 
            ]
        )
    )

    flags_df = _build_patient_level_clinical_flags(
        dataframe=df_clean,
        patient_col=patient_col,
    )

    df_static = df_clean.select(selected_columns).unique(
        subset=[patient_col], keep="first"
    )

    static_features = build_static_feature_list(
        dataframe=df_static,
        generated_dummy_columns=generated_dummy_columns,
        config_mode_name=config_mode_name,
        final_features=final_features,
    )

    pd_static = df_static.to_pandas()

    keep_for_tableone = {
        col
        for col in generated_dummy_columns
        if col.startswith("icu_ghm_") or col.startswith("icu_mode_entree_")
    }
    drop_columns = [
        col
        for col in generated_dummy_columns
        if col in pd_static.columns and col not in keep_for_tableone
    ]
    pd_static = pd_static.drop(columns=drop_columns)

    pd_categorical = (
        categorical_data.unique(subset=[patient_col], keep="first").to_pandas()
    )

    pd_static = pd_static.merge(
        pd_categorical,
        on=patient_col,
        how="left",
        suffixes=("", "_categorical"),
    )

    # Fusion avec la variable Sepsis calculée
    pd_static = pd_static.merge(
        sepsis_df.to_pandas(), on=patient_col, how="left"
    )

    pd_static = _translate_tableone_categories(pd_static)

    # Nettoyage des colonnes complexes/listes
    for col in pd_static.columns:
        sample = pd_static[col].dropna().iloc[0:1]
        if len(sample) > 0 and isinstance(
            sample.iloc[0], (list, np.ndarray, pl.Series)
        ):
            pd_static = pd_static.drop(columns=[col])

    # Merge patient-level flags
    if not flags_df.is_empty():
        pd_flags = flags_df.to_pandas()
        for flag_col in pd_flags.columns:
            if flag_col != patient_col and pd.api.types.is_bool_dtype(
                pd_flags[flag_col]
            ):
                pd_flags[flag_col] = pd_flags[flag_col].astype(int)
        pd_static = pd_static.merge(
            pd_flags,
            on=patient_col,
            how="left",
        )

    # -------------------------------------------------------------------------
    # 1. GESTION DU SAPS II ET DE SES MANQUANTS
    # -------------------------------------------------------------------------
    if "sapsii" in pd_static.columns:
        pd_static["sapsii"] = pd.to_numeric(
            pd_static["sapsii"], errors="coerce"
        )
        pd_static["sapsii_missing"] = (
            pd_static["sapsii"].isna().astype(int)
        )

    continuous_features = [
        feature
        for feature in [
            "age",
            "sapsii",
            "score_glasgow",
            "real_time_hours",
            "observed_duration",
            "los",
        ]
        if feature in static_features or feature in pd_static.columns
    ]

    for feature in continuous_features:
        pd_static[feature] = pd.to_numeric(
            pd_static[feature],
            errors="coerce",
        )

    categorical_features = [
        feature
        for feature in categorical_source_columns
        if feature in pd_static.columns
        and feature not in continuous_features
    ]

    for feature in ["gender", target_col, "sepsis", "sapsii_missing"]:
        if (
            feature in pd_static.columns
            and feature not in categorical_features
            and feature not in continuous_features
        ):
            categorical_features.append(feature)

    clinical_flags = [
        "had_dialyse",
        "had_vasoactive_drugs",
        "was_conscious",
        "was_ventilated",
    ]
    for flag in clinical_flags:
        if (
            flag in pd_static.columns
            and flag not in categorical_features
            and flag not in continuous_features
        ):
            categorical_features.append(flag)

    # Dedummying des variables GHM / Entrée
    pd_static = _dedummy_categorical_columns(
        dataframe=pd_static,
        prefix="icu_ghm_",
        output_column="icu_ghm",
    )
    pd_static = _dedummy_categorical_columns(
        dataframe=pd_static,
        prefix="icu_mode_entree_",
        output_column="icu_mode_entree",
    )

    # -------------------------------------------------------------------------
    # Extraction des Top 5 GHM en variables binaires décalées
    # -------------------------------------------------------------------------
    if "icu_ghm" in pd_static.columns:
        top_5_ghm = (
            pd_static["icu_ghm"]
            .dropna()[
                ~pd_static["icu_ghm"]
                .dropna()
                .str.lower()
                .isin(["others", "unknown", "autre", "autres"])
            ]
            .value_counts()
            .head(5)
            .index.tolist()
        )

        for ghm_label in top_5_ghm:
            display_col_name = f"{ghm_label}"
            pd_static[display_col_name] = (pd_static["icu_ghm"] == ghm_label).astype(int)
            
            if display_col_name not in categorical_features:
                categorical_features.append(display_col_name)

        pd_static = pd_static.drop(columns=["icu_ghm"])
        if "icu_ghm" in categorical_features:
            categorical_features.remove("icu_ghm")

    # -------------------------------------------------------------------------
    # 2. FILTRAGE DES CATEGORIES DE ICU_GHM
    # -------------------------------------------------------------------------
    if "icu_ghm" in pd_static.columns and top_n_ghm is not None:
        top_ghm_cats = (
            pd_static["icu_ghm"].value_counts().head(top_n_ghm).index.tolist()
        )
        pd_static["icu_ghm"] = pd_static["icu_ghm"].apply(
            lambda x: x if x in top_ghm_cats else "Autres GHM"
        )

    for reconstructed_col in ["icu_ghm", "icu_mode_entree"]:
        if (
            reconstructed_col in pd_static.columns
            and reconstructed_col not in categorical_features
            and reconstructed_col not in continuous_features
        ):
            categorical_features.append(reconstructed_col)

    # Tri des catégories par fréquence
    for col in ["icu_ghm", "icu_mode_entree", "gender"]:
        if col in pd_static.columns:
            freq_order = pd_static[col].value_counts().index.tolist()
            pd_static[col] = pd.Categorical(
                pd_static[col], categories=freq_order, ordered=True
            )

    describe_columns = [
        *continuous_features,
        *categorical_features,
    ]
    describe_columns = list(dict.fromkeys(describe_columns))

    if not describe_columns:
        raise ValueError(
            "No static features are available for the descriptive table."
        )

    binary_indicator_features = _find_binary_indicator_features(
        dataframe=pd_static,
        categorical_features=categorical_features,
    )

    _ordered_categorical_cols = {
        col
        for col in pd_static.columns
        if isinstance(pd_static[col].dtype, pd.CategoricalDtype)
        and pd_static[col].cat.ordered
    }
    for col in pd_static.columns:
        if pd.api.types.is_bool_dtype(pd_static[col]):
            pd_static[col] = pd_static[col].astype(int)
        elif pd.api.types.is_numeric_dtype(pd_static[col]):
            pass
        elif col not in _ordered_categorical_cols:
            pd_static[col] = pd_static[col].astype(str)

    TABLEONE_COLUMN_DISPLAY_NAMES.update(
        {
            "sapsii": "SAPS II Score",
            "sapsii_missing": "SAPS II Missing",
            "sepsis": "Sepsis Diagnosis",
            "los": "Length of Stay (hours)",
        }
    )

    rename_mask: dict[str, str] = {
        col: display_name
        for col, display_name in TABLEONE_COLUMN_DISPLAY_NAMES.items()
        if col in pd_static.columns
    }
    pd_static = pd_static.rename(columns=rename_mask)

    _rename_feature = lambda name: rename_mask.get(name, name)
    continuous_features = [_rename_feature(f) for f in continuous_features]
    categorical_features = [_rename_feature(f) for f in categorical_features]
    describe_columns = [_rename_feature(f) for f in describe_columns]
    binary_indicator_features = [
        _rename_feature(f) for f in binary_indicator_features
    ]

    table = TableOne(
        data=pd_static,
        columns=describe_columns,
        categorical=categorical_features,
        continuous=continuous_features,
        pval=False,
        decimals=2,
        missing=False,
    )

    positive_binary_table = _keep_positive_level_for_binary_features(
        table_dataframe=table.tableone,
        binary_features=binary_indicator_features,
    )

    formatted_table = add_variable_type_sections(
        table_dataframe=positive_binary_table,
        continuous_features=continuous_features,
        categorical_features=categorical_features,
    )

    _sort_cols = {"ICU Disease Group", "ICU Entry Mode"}
    formatted_table = _sort_categorical_rows_by_frequency(
        table_dataframe=formatted_table,
        features_to_sort=_sort_cols,
    )

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    formatted_table.to_html(output_dir / "tableone_static_features.html")
    formatted_table.to_csv(output_dir / "tableone_static_features.csv")
    formatted_table.to_latex(output_dir / "tableone_static_features.tex")

    return table